services:
  pp-api:
    container_name: pp-api
    image: pp-api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      PORT: ${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    restart: always

  pp-app:
    container_name: pp-app
    image: pp-app
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      PORT: ${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: always